services:
  batrium-watchmon-udp:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: batrium-watchmon-udp:latest
    container_name: batrium-watchmon-udp
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./config:/data
